#!/bin/bash

service logstash status | grep 'is running' &> /dev/null
if [ "$?" != "0" ]; then echo "ERROR: logstash not running"; exit 1; fi

# Try connect to logstash redis server
nc -z 192.168.33.10 6379
if [ "$?" != "0" ]; then echo "ERROR: redis-server not responding on port 6379"; exit 1; fi

# This test is too fragile
#logger "mojje log message"
#sleep 60
#curl  '192.168.33.10:9200/_search?q=host:mojje&pretty'  | grep mojje &> /dev/null
#if [ "$?" != "0" ]; then echo "ERROR: No log messages for mojje"; exit 1; fi

echo "=====SUCCESS====="

