#!/bin/bash

service logstash status | grep 'start/running' &> /dev/null
if [ "$?" != "0" ]; then echo "ERROR: logstash not running"; exit 1; fi

service elasticsearch status | grep running &> /dev/null
if [ "$?" != "0" ]; then echo "ERROR: elasticsearch not running"; exit 1; fi

service redis-server status | grep running &> /dev/null
if [ "$?" != "0" ]; then echo "ERROR: redis-server not running"; exit 1; fi
nc -z localhost 6379
if [ "$?" != "0" ]; then echo "ERROR: redis-server not responding on port 6379"; exit 1; fi

echo "=====SUCCESS====="

